"use client";
import { add } from "@/lib/firebase/firestore";
// import { update } from "@/lib/firebase/firestore";
// import { SignJWT } from "jose";
export default function Test() {
  const analytics = {
    rooms: {
      categories: {
        executive: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 80000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 78000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 76000,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 58000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 7790,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 78000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 7,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 62000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Executive",
        },
        deluxe: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 81000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 79000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 78000,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 75000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 74000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 7790,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 7,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 71000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            5: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Deluxe",
        },
        suite: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 138000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 135000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 13790,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 17900,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 129000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 81000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 128000,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 128000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Suite",
        },
        "super suite": {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 76000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 74000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 62000,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 7,
              avgPriceOfFood: 0,
              totalEarnings: 59000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 7,
              totalEarnings: 60000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 58000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 7,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 7,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 56000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 7,
              avgPriceOfRooms: 0,
            },
          },
          name: "Super Suite",
        },
      },
    },
    food: {
      categories: {
        "in-house restaurant": {
          weeks: {
            20: {
              totalEarnings: 0,
              avgDiningDuration: 0,
              totalBookings: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
          },
          days: {
            135: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 41000,
              avgPriceOfFood: 0,
            },
            134: {
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 39000,
              avgPricPerOrder: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              avgDiningDuration: 0,
              totalBookings: 10,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalEarnings: 38000,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            132: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              avgPriceOfFood: 0,
              totalEarnings: 35000,
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            131: {
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalBookings: 10,
              totalEarnings: 3790,
              avgPriceOfFood: 0,
              avgPricPerOrder: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgDiningDuration: 0,
              avgPricPerOrder: 0,
              totalEarnings: 32000,
              totalBookings: 10,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
            },
            129: {
              avgPricPerOrder: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 10,
              avgDiningDuration: 0,
              totalEarnings: 7900,
            },
          },
          months: {
            3: {
              totalIssues: 0,
              avgPrice: 0,
              totalEarnings: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalBookings: 10,
              avgPricPerOrder: 0,
            },
          },
          name: "In-house Restaurant",
        },
        restaurant: {
          weeks: {
            20: {
              totalEarnings: 0,
              avgDiningDuration: 0,
              totalBookings: 10,
              totalIssues: 0,
              avgPricPerOrder: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
          },
          days: {
            135: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 51000,
              avgPriceOfFood: 0,
            },
            134: {
              totalBookings: 10,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalEarnings: 49000,
              avgPricPerOrder: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              avgDiningDuration: 0,
              totalBookings: 10,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalEarnings: 48000,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            132: {
              avgPrice: 0,
              totalIssues: 0,
              avgPricPerOrder: 0,
              totalBookings: 10,
              avgPriceOfFood: 0,
              totalEarnings: 4790,
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
            },
            131: {
              avgDiningDuration: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalBookings: 10,
              totalEarnings: 45000,
              avgPriceOfFood: 0,
              avgPricPerOrder: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgDiningDuration: 0,
              avgPricPerOrder: 0,
              totalEarnings: 41000,
              totalBookings: 10,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
            },
            129: {
              avgPricPerOrder: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 10,
              avgDiningDuration: 0,
              totalEarnings: 40000,
            },
          },
          months: {
            3: {
              totalIssues: 0,
              avgPrice: 0,
              totalEarnings: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalOrdersOnline: 0,
              totalOrdersForDelivery: 0,
              totalOrdersForTakeaway: 0,
              avgPriceForOrdersOnline: 0,
              avgPriceForOrdersDelivery: 0,
              avgPriceForOrdersTakeaway: 0,
              avgDiningDuration: 0,
              totalBookings: 0,
              avgPricPerOrder: 0,
            },
          },
          name: "Restaurant",
        },
      },
    },
    services: {
      categories: {
        spa: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 31000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 29000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 28000,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 25000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 2790,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 28000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 31000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 5,
              avgPriceOfRooms: 0,
            },
          },
          name: "Spa",
        },
        gym: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 7400,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 24000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 22000,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 20000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 18000,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 21000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 15000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 5,
              avgPriceOfRooms: 0,
            },
          },
          name: "Gym",
        },
        laundry: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 21000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 19000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 18000,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 15000,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 1790,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 11000,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 14000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 5,
              avgPriceOfRooms: 0,
            },
          },
          name: "Laundry",
        },
        pool: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 36000,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 34000,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 32000,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 5,
              avgPriceOfFood: 0,
              totalEarnings: 7900,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 5,
              totalEarnings: 7800,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 7400,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 5,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 25000,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 0,
              avgPriceOfRooms: 0,
            },
          },
          name: "Pool",
        },
      },
    },
    issues: {
      categories: {
        rooms: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 32,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 25,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 62,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 2,
              avgPriceOfFood: 0,
              totalEarnings: 46,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalEarnings: 22,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 15,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 2,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 23,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 2,
              avgPriceOfRooms: 0,
            },
          },
          name: "Rooms",
        },
        Food: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 14,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 11,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 13,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 2,
              avgPriceOfFood: 0,
              totalEarnings: 15,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalEarnings: 19,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 12,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 2,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 16,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 2,
              avgPriceOfRooms: 0,
            },
          },
          name: "Food",
        },
        services: {
          weeks: {
            20: {
              avgPriceOfServices: 0,
              totalEarnings: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromServices: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
            },
          },
          days: {
            135: {
              avgPriceOfServices: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 8,
              totalServiceRequests: 0,
              avgPriceOfFood: 0,
            },
            134: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalFoodOrders: 0,
              avgStayDuration: 0,
              totalEarnings: 5,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalIssues: 0,
              avgPrice: 0,
            },
            133: {
              totalEarningsFromServices: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfRooms: 0,
              totalEarnings: 7,
              totalFoodOrders: 0,
            },
            132: {
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              totalEarningsFromServices: 0,
              avgPriceOfRooms: 0,
              totalBookings: 2,
              avgPriceOfFood: 0,
              totalEarnings: 1,
              avgStayDuration: 0,
              totalFoodOrders: 0,
            },
            131: {
              totalServiceRequests: 0,
              avgPriceOfMinibar: 0,
              avgStayDuration: 0,
              totalFoodOrders: 0,
              totalIssues: 0,
              totalEarningsFromMinibar: 0,
              avgPrice: 0,
              avgPriceOfServices: 0,
              totalBookings: 2,
              totalEarnings: 9,
              totalEarningsFromServices: 0,
              avgPriceOfFood: 0,
              avgPriceOfRooms: 0,
            },
            130: {
              avgPriceOfFood: 0,
              avgStayDuration: 0,
              avgPriceOfServices: 0,
              avgPriceOfRooms: 0,
              avgPriceOfMinibar: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 4,
              totalServiceRequests: 0,
              totalEarningsFromMinibar: 0,
              totalBookings: 2,
              totalIssues: 12,
              totalFoodOrders: 0,
              avgPrice: 0,
            },
            129: {
              avgPriceOfRooms: 0,
              totalIssues: 0,
              totalFoodOrders: 0,
              avgPrice: 0,
              avgPriceOfFood: 0,
              totalBookings: 2,
              totalEarningsFromServices: 0,
              avgPriceOfMinibar: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalEarningsFromMinibar: 0,
              totalEarnings: 5,
              avgPriceOfServices: 0,
            },
          },
          months: {
            3: {
              avgPriceOfServices: 0,
              avgPriceOfMinibar: 0,
              totalIssues: 0,
              avgPrice: 0,
              totalEarningsFromServices: 0,
              totalEarnings: 0,
              totalEarningsFromMinibar: 0,
              avgPriceOfFood: 0,
              totalFoodOrders: 0,
              totalServiceRequests: 0,
              avgStayDuration: 0,
              totalBookings: 0,
              avgPriceOfRooms: 0,
            },
          },
          name: "Services",
        },
      },
    },
  };

  // let usr;

  const handleUser = async () => {
    // const variables = [
    //   "0143161875/1", // Reservation No
    //   "301", // Room No
    //   "10 March 2025", // Check-in
    //   "15 March 2025", // Check-out
    //   "5", // Nights
    //   "₹5000", // Room Rate
    //   "₹25000", // Total Price
    //   "123-456-7890", // Hotel Contact 1
    //   "987-654-3210", // Hotel Contact 2
    //   "https://hotelbuildbility.com/concierge", // Concierge Link
    // ];
    // const user = await sendWhatsAppMessage("918851280284", variables);
    const user = await add("vikumar.azad@gmail.com", analytics, "analytics");
    // const secretKey = new TextEncoder().encode("Vikas@1234");

    // const payload = {
    //   email: "vikumar.azad@gmail.com",e
    //   tableNo: "6",
    //   tax: { gstPercentage: "" },
    // };
    // // const hashedPassword = await hash("123457789", 8);
    // const token = await new SignJWT(payload)
    //   .setProtectedHeader({ alg: "HS256" }) // Set the signing algorithm
    //   // Do not set `.setExpirationTime()` to omit the expiration claim
    //   .sign(secretKey);

    // return token;
    console.log(user);
    // console.log(data);
  };
  // handleUser().then((token) => {
  //   console.log("JWT Token:", token);
  // });
  return (
    <div>
      {/* <h1>{JSON.stringify(usr)}</h1> */}
      <button onClick={() => handleUser()}>Click</button>
    </div>
  );
}
