"use client";
import { add } from "@/lib/firebase/firestore";
// import { update } from "@/lib/firebase/firestore";
// import { SignJWT } from "jose";

export default function Test() {
  const inventory = {
    store: {
      items: [
        {
          sku: "ITEM001",
          name: "Widget A",
          description: "A useful widget",
          category: "Tools",
          quantity: 5,
          unitPrice: 10.5,
          reorderLevel: 15,
          supplier: "Supplier X",
          supplierGst: "GST123456",
          quantityUnit: "pcs",
          batchNo: "BATCH2024",
          date: "2024-02-28",
          paymentMode: "Credit Card",
          amount: 52.5,
        },
        {
          sku: "ITEM002",
          name: "Gadget B",
          description: "A high-tech gadget",
          category: "Electronics",
          quantity: 3,
          unitPrice: 25.0,
          reorderLevel: 10,
          supplier: "Supplier Y",
          supplierGst: "GST654321",
          quantityUnit: "pcs",
          batchNo: "BATCH2025",
          date: "2024-02-27",
          paymentMode: "Bank Transfer",
          amount: 75.0,
        },
        {
          sku: "ITEM003",
          name: "Hammer",
          description: "Steel claw hammer",
          category: "Tools",
          quantity: 12,
          unitPrice: 15.0,
          reorderLevel: 8,
          supplier: "Supplier X",
          supplierGst: "GST123456",
          quantityUnit: "pcs",
          batchNo: "BATCH2026",
          date: "2024-02-26",
          paymentMode: "Cash",
          amount: 180.0,
        },
        {
          sku: "ITEM004",
          name: "Screwdriver Set",
          description: "Multi-size screwdriver set",
          category: "Tools",
          quantity: 2,
          unitPrice: 20.0,
          reorderLevel: 5,
          supplier: "Supplier Z",
          supplierGst: "GST789123",
          quantityUnit: "set",
          batchNo: "BATCH2027",
          date: "2024-02-25",
          paymentMode: "UPI",
          amount: 40.0,
        },
        {
          sku: "ITEM005",
          name: "Office Chair",
          description: "Ergonomic office chair",
          category: "Furniture",
          quantity: 1,
          unitPrice: 150.0,
          reorderLevel: 3,
          supplier: "Supplier A",
          supplierGst: "GST159753",
          quantityUnit: "pcs",
          batchNo: "BATCH2028",
          date: "2024-02-24",
          paymentMode: "Credit Card",
          amount: 150.0,
        },
        {
          sku: "ITEM006",
          name: "Desk Lamp",
          description: "Adjustable LED desk lamp",
          category: "Electronics",
          quantity: 0,
          unitPrice: 30.0,
          reorderLevel: 5,
          supplier: "Supplier Y",
          supplierGst: "GST654321",
          quantityUnit: "pcs",
          batchNo: "BATCH2029",
          date: "2024-02-23",
          paymentMode: "Debit Card",
          amount: 0.0,
        },
        {
          sku: "ITEM007",
          name: "Printer Paper",
          description: "A4 size printer paper, 500 sheets",
          category: "Office Supplies",
          quantity: 25,
          unitPrice: 8.5,
          reorderLevel: 20,
          supplier: "Supplier A",
          supplierGst: "GST159753",
          quantityUnit: "pack",
          batchNo: "BATCH2030",
          date: "2024-02-22",
          paymentMode: "Cash",
          amount: 212.5,
        },
        {
          sku: "ITEM008",
          name: "Whiteboard Markers",
          description: "Set of 4 colors",
          category: "Office Supplies",
          quantity: 10,
          unitPrice: 5.0,
          reorderLevel: 15,
          supplier: "Supplier A",
          supplierGst: "GST159753",
          quantityUnit: "set",
          batchNo: "BATCH2031",
          date: "2024-02-21",
          paymentMode: "Bank Transfer",
          amount: 50.0,
        },
        {
          sku: "ITEM009",
          name: "Laptop Stand",
          description: "Adjustable height aluminum stand",
          category: "Electronics",
          quantity: 7,
          unitPrice: 40.0,
          reorderLevel: 5,
          supplier: "Supplier Z",
          supplierGst: "GST789123",
          quantityUnit: "pcs",
          batchNo: "BATCH2032",
          date: "2024-02-20",
          paymentMode: "Credit Card",
          amount: 280.0,
        },
        {
          sku: "ITEM010",
          name: "USB-C Hub",
          description: "6-in-1 multiport adapter",
          category: "Electronics",
          quantity: 2,
          unitPrice: 60.0,
          reorderLevel: 4,
          supplier: "Supplier Y",
          supplierGst: "GST654321",
          quantityUnit: "pcs",
          batchNo: "BATCH2033",
          date: "2024-02-19",
          paymentMode: "UPI",
          amount: 120.0,
        },
        {
          sku: "ITEM011",
          name: "Wireless Mouse",
          description: "Bluetooth wireless mouse",
          category: "Electronics",
          quantity: 6,
          unitPrice: 25.0,
          reorderLevel: 10,
          supplier: "Supplier Y",
          supplierGst: "GST654321",
          quantityUnit: "pcs",
          batchNo: "BATCH2034",
          date: "2024-02-18",
          paymentMode: "Credit Card",
          amount: 150.0,
        },
        {
          sku: "ITEM012",
          name: "Notebook",
          description: "A5 size ruled notebook, 200 pages",
          category: "Office Supplies",
          quantity: 15,
          unitPrice: 3.0,
          reorderLevel: 10,
          supplier: "Supplier A",
          supplierGst: "GST159753",
          quantityUnit: "pcs",
          batchNo: "BATCH2035",
          date: "2024-02-17",
          paymentMode: "UPI",
          amount: 45.0,
        },
        {
          sku: "ITEM013",
          name: "Extension Cord",
          description: "5-socket power extension cord",
          category: "Electronics",
          quantity: 4,
          unitPrice: 15.0,
          reorderLevel: 5,
          supplier: "Supplier Z",
          supplierGst: "GST789123",
          quantityUnit: "pcs",
          batchNo: "BATCH2036",
          date: "2024-02-16",
          paymentMode: "Bank Transfer",
          amount: 60.0,
        },
        {
          sku: "ITEM014",
          name: "Desk Organizer",
          description: "Multi-compartment desk organizer",
          category: "Furniture",
          quantity: 9,
          unitPrice: 12.0,
          reorderLevel: 10,
          supplier: "Supplier A",
          supplierGst: "GST159753",
          quantityUnit: "pcs",
          batchNo: "BATCH2037",
          date: "2024-02-15",
          paymentMode: "Cash",
          amount: 108.0,
        },
        {
          sku: "ITEM015",
          name: "Safety Gloves",
          description: "Cut-resistant industrial gloves",
          category: "Tools",
          quantity: 2,
          unitPrice: 8.0,
          reorderLevel: 5,
          supplier: "Supplier X",
          supplierGst: "GST123456",
          quantityUnit: "pair",
          batchNo: "BATCH2038",
          date: "2024-02-14",
          paymentMode: "Debit Card",
          amount: 16.0,
        },
        {
          sku: "ITEM016",
          name: "Electric Drill",
          description: "Cordless rechargeable drill",
          category: "Tools",
          quantity: 3,
          unitPrice: 80.0,
          reorderLevel: 5,
          supplier: "Supplier X",
          supplierGst: "GST123456",
          quantityUnit: "pcs",
          batchNo: "BATCH2039",
          date: "2024-02-13",
          paymentMode: "Credit Card",
          amount: 240.0,
        },
        {
          sku: "ITEM017",
          name: "File Cabinet",
          description: "Steel 4-drawer file cabinet",
          category: "Furniture",
          quantity: 1,
          unitPrice: 220.0,
          reorderLevel: 2,
          supplier: "Supplier A",
          supplierGst: "GST159753",
          quantityUnit: "pcs",
          batchNo: "BATCH2040",
          date: "2024-02-12",
          paymentMode: "UPI",
          amount: 220.0,
        },
        {
          sku: "ITEM018",
          name: "Coffee Maker",
          description: "Automatic drip coffee machine",
          category: "Electronics",
          quantity: 2,
          unitPrice: 65.0,
          reorderLevel: 3,
          supplier: "Supplier Z",
          supplierGst: "GST789123",
          quantityUnit: "pcs",
          batchNo: "BATCH2041",
          date: "2024-02-11",
          paymentMode: "Cash",
          amount: 130.0,
        },
        {
          sku: "ITEM019",
          name: "Packing Tape",
          description: "Heavy-duty brown packing tape",
          category: "Office Supplies",
          quantity: 18,
          unitPrice: 4.5,
          reorderLevel: 10,
          supplier: "Supplier A",
          supplierGst: "GST159753",
          quantityUnit: "roll",
          batchNo: "BATCH2042",
          date: "2024-02-10",
          paymentMode: "Bank Transfer",
          amount: 81.0,
        },
        {
          sku: "ITEM020",
          name: "Bluetooth Speaker",
          description: "Portable Bluetooth speaker",
          category: "Electronics",
          quantity: 3,
          unitPrice: 50.0,
          reorderLevel: 5,
          supplier: "Supplier Y",
          supplierGst: "GST654321",
          quantityUnit: "pcs",
          batchNo: "BATCH2043",
          date: "2024-02-09",
          paymentMode: "Credit Card",
          amount: 150.0,
        },
      ],
      categories: [
        {
          name: "Tools",
          description: "Hand tools and power tools",
          updatedBy: "Admin",
          lastUpdated: "2024-02-25T12:30:00Z",
        },
        {
          name: "Electronics",
          description: "Electronic gadgets and devices",
          updatedBy: "Manager",
          lastUpdated: "2024-02-26T15:45:00Z",
        },
        {
          name: "Furniture",
          description: "Office and home furniture",
          updatedBy: "Admin",
          lastUpdated: "2024-02-26T10:15:00Z",
        },
        {
          name: "Office Supplies",
          description: "Stationery and office essentials",
          updatedBy: "Manager",
          lastUpdated: "2024-02-27T09:30:00Z",
        },
      ],
      suppliers: [
        {
          name: "Supplier X",
          phoneNumber: "+1234567890",
          email: "supplierx@example.com",
          address: "123 Industrial Ave, City",
          gstNumber: "GST123456",
        },
        {
          name: "Supplier Y",
          phoneNumber: "+0987654321",
          email: "suppliery@example.com",
          address: "456 Tech Park, City",
          gstNumber: "GST654321",
        },
        {
          name: "Supplier Z",
          phoneNumber: "+1122334455",
          email: "supplierz@example.com",
          address: "789 Market Road, City",
          gstNumber: "GST789123",
        },
        {
          name: "Supplier A",
          phoneNumber: "+5566778899",
          email: "suppliera@example.com",
          address: "999 Office Blvd, City",
          gstNumber: "GST159753",
        },
      ],
      recentTransactions: [
        {
          id: "TRANS001",
          name: "Widget A",
          sku: "ITEM001",
          category: "Tools",
          quantity: 2,
          transactionType: "Sale",
          dateTime: "2024-02-28T10:15:00Z",
          supplierCustomer: "Customer Z",
        },
        {
          id: "TRANS002",
          name: "Gadget B",
          sku: "ITEM002",
          category: "Electronics",
          quantity: 1,
          transactionType: "Purchase",
          dateTime: "2024-02-27T14:20:00Z",
          supplierCustomer: "Supplier Y",
        },
        {
          id: "TRANS003",
          name: "Screwdriver Set",
          sku: "ITEM004",
          category: "Tools",
          quantity: 1,
          transactionType: "Return",
          dateTime: "2024-02-26T18:00:00Z",
          supplierCustomer: "Customer A",
        },
        {
          id: "TRANS004",
          name: "Office Chair",
          sku: "ITEM005",
          category: "Furniture",
          quantity: 1,
          transactionType: "Sale",
          dateTime: "2024-02-25T16:30:00Z",
          supplierCustomer: "Customer B",
        },
        {
          id: "TRANS005",
          name: "Desk Lamp",
          sku: "ITEM006",
          category: "Electronics",
          quantity: 1,
          transactionType: "Sale",
          dateTime: "2024-02-24T12:45:00Z",
          supplierCustomer: "Customer C",
        },
      ],
    },
  };

  // let usr;
  const handleUser = async () => {
    const user = await add("vikumar.azad@gmail.com", inventory, "inventory");
    // const secretKey = new TextEncoder().encode("Vikas@1234");

    // const payload = {
    //   email: "vikumar.azad@gmail.com",e
    //   tableNo: "6",
    //   tax: { gstPercentage: "" },
    // };
    // // const hashedPassword = await hash("123456789", 8);
    // const token = await new SignJWT(payload)
    //   .setProtectedHeader({ alg: "HS256" }) // Set the signing algorithm
    //   // Do not set `.setExpirationTime()` to omit the expiration claim
    //   .sign(secretKey);

    // return token;
    console.log(user);
    // console.log(data);
  };
  // handleUser().then((token) => {
  //   console.log("JWT Token:", token);
  // });
  return (
    <div>
      {/* <h1>{JSON.stringify(usr)}</h1> */}
      <button onClick={() => handleUser()}>Click</button>
    </div>
  );
}
